# Generated by Django 3.0.4 on 2020-11-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('pk_city', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('pk_department', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('pk_designation', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='function_category',
            fields=[
                ('pk_function_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('pk_location', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('pk_status_code', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='template_variables',
            fields=[
                ('pk_field_code', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('db_table_name', models.CharField(max_length=100)),
                ('sort_column', models.CharField(default='name', max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('pk_vendor', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.location')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('pk_team', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('function_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.function_category')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='sub_team',
            fields=[
                ('pk_sub_team', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('pk_state', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
                ('sub_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.sub_team')),
            ],
        ),
        migrations.CreateModel(
            name='report_type',
            fields=[
                ('pk_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('pk_region', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('pk_gender', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
        migrations.AddField(
            model_name='function_category',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
        migrations.CreateModel(
            name='frequency',
            fields=[
                ('pk_frequency', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('udaan_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('doj', models.DateField()),
                ('lwd', models.DateField()),
                ('reporting_manager_1', models.CharField(max_length=100)),
                ('reporting_manager_2', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.city')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.designation')),
                ('function_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.function_category')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.location')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.state')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
                ('sub_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.sub_team')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.team')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='dimensions',
            fields=[
                ('pk_dimension', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('fk_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.template_variables')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
        migrations.AddField(
            model_name='designation',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
    ]
