# Generated by Django 3.1.2 on 2020-11-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='sub_team',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='location',
        ),
        migrations.AddField(
            model_name='state',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.department'),
        ),
        migrations.AddField(
            model_name='sub_team',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.city'),
        ),
        migrations.AddField(
            model_name='sub_team',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.location'),
        ),
        migrations.AddField(
            model_name='sub_team',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.state'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.department'),
        ),
    ]
