# Generated by Django 3.1.2 on 2020-11-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenure',
            fields=[
                ('pk_tenure', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='exit_type',
            fields=[
                ('pk_exit_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='employment_type',
            fields=[
                ('pk_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='ctc_slab',
            fields=[
                ('pk_ctc', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='age',
            fields=[
                ('pk_age', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
    ]
