# Generated by Django 3.1.2 on 2020-11-02 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0002_auto_20201102_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='active_inactive',
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
    ]
