# Generated by Django 3.1.3 on 2020-11-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0002_auto_20201118_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
