# Generated by Django 3.1.2 on 2020-11-03 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0002_age_ctc_slab_employment_type_exit_type_tenure'),
    ]

    operations = [
        migrations.CreateModel(
            name='entity',
            fields=[
                ('pk_entity', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status')),
            ],
        ),
    ]
