# Generated by Django 3.1.3 on 2020-11-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0003_auto_20201118_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='udaan_id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
