# Generated by Django 3.1.2 on 2020-11-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0003_auto_20201102_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
        migrations.AddField(
            model_name='designation',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
        migrations.AddField(
            model_name='function_category',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
        migrations.AddField(
            model_name='state',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
        migrations.AddField(
            model_name='sub_team',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.status'),
        ),
    ]
