# Generated by Django 3.1.3 on 2020-11-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0004_auto_20201118_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
