# Generated by Django 3.1.3 on 2020-11-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0005_auto_20201118_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lwd',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
